Jjdzr10 bd 16
infoshareacademy/JJDZR10-BugDoom pull request #19
Opened 2023-03-31 20:25 UTC by filip-piatkowski

Widok szczegółów pojedyńczej trasy.

2023-04-02 15:05 UTC, JewstafiewJakub requested changes

2023-04-02 15:05 UTC, JewstafiewJakub commented on BugDoom - web app/pom.xml
> +		</dependency>
Nie potrzebujemy tej zależności

2023-04-02 15:05 UTC, JewstafiewJakub commented on BugDoom - web app/src/main/resources/templates/tracks/track-error.html
> +    Wybrany wyścig nie istnieje. Proszę spróbuj ponownie.
wyścig -> trasa

2023-04-02 19:25 UTC, grzeslukasik approved these changes

2023-04-02 19:25 UTC, grzeslukasik commented on BugDoom/pom.xml
proponuję w templates utworzyć podfolder tracks i tam wrzucić track-detalis, track-error, track

2023-04-04 07:52 UTC, szablewski reviewed
jak poprawisz uwagi kolegów to będzie ok

2023-04-06 18:38 UTC, filip-piatkowski reviewed
Zamiany poprawione i wypushowane.

2023-04-06 18:38 UTC, filip-piatkowski commented on BugDoom - web app/pom.xml
> +		</dependency>
Poprawione

2023-04-06 18:38 UTC, filip-piatkowski commented on BugDoom - web app/src/main/resources/templates/tracks/track-error.html
> +    Wybrany wyścig nie istnieje. Proszę spróbuj ponownie.
Poprawione.

2023-04-06 18:38 UTC, filip-piatkowski commented on BugDoom/pom.xml
Poprawione.

2023-04-06 19:01 UTC, szablewski approved these changes
ok

2023-04-11 19:39 UTC, JewstafiewJakub approved these changes

2023-04-16 10:05 UTC, merged