Jjdzr10 bd 32
infoshareacademy/JJDZR10-BugDoom pull request #27
Opened 2023-05-02 22:29 UTC by agnieszka-pa

2023-05-04 12:40 UTC, JakubGrotha requested changes

2023-05-04 12:40 UTC, JGrotha commented on BugDoom - web app/src/main/java/com/infoshareacademy/pl/controller/DashboardController.java
> +        model.addAttribute("Dashboard", "dashboard");
po co jest ten model? Nie jest używany w MainMenu.html + to jest tylko String, więc nie za bardzo wydaje mi się, żeby był użyteczny

2023-05-04 16:59 UTC, agnieszka-pa commented on BugDoom - web app/src/main/java/com/infoshareacademy/pl/controller/DashboardController.java
> +        model.addAttribute("Dashboard", "dashboard");
naprawione

2023-05-04 17:30 UTC, JakubGrotha approved these changes

2023-05-05 06:18 UTC, szablewski approved these changes

2023-05-05 11:57 UTC, grzeslukasik approved these changes

2023-05-05 17:09 UTC, merged